#!/bin/sh
set -e

composer install

bin/console ca:cl
symfony server:stop

echo "---- DB Check ----"
if bin/console do:d:c; then
  bin/console d:s:u --force && bin/console doctrine:migrations:migrate
fi
echo "---- DB should be ready ----"

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"